{% set name = "yaqd-wright" %}
{% set version = "2022.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-wright-{{ version }}.tar.gz
  sha256: 22ad55246e21aee8763e0cf1ae469970b248bcbfeeabbaf9b3412281a7d20065

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-wright-aerotech = yaqd_wright._wright_aerotech:WrightAerotech.main
    - yaqd-wright-stepper-box = yaqd_wright._wright_stepper_box:WrightStepperBox.main
    - yaqd-wright-ingaas = yaqd_wright._wright_ingaas:WrightInGaAs.main
    - yaqd-wright-wl-motor = yaqd_wright._wright_wl_motor:WrightWlMotor.main
    - yaqd-ndinterp = yaqd_wright._ndinterp:NDInterp.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.7
  run:
    - numpy
    - pyserial
    - python >=3.7
    - yaqd-core >=2020.06.3
    - yaqc
    - wrighttools
    - scipy

test:
  imports:
    - yaqd_wright
  commands:
    - pip check
    - yaqd-wright-aerotech --help
    - yaqd-wright-filter-wheel --help
    - yaqd-wright-ingaas --help
    - yaqd-wright-wl-motor --help
    - yaqd-ndinterp --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for wright group specific hardware, collected together
  dev_url: https://github.com/wright-group/yaqd-wright
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - ddkohler
    - darienmorrow
    - kameyer226
